on: ["pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: LaTeX Action
        uses: fudan-mse/latex-action@v0.0.1
        with:
          root_file: main.tex
          working_directory:
          compiler:
          args:
          extra_packages:
          extra_system_packages:
